"""Freeze the REC-01 legacy repros as NEWCORE NC-02 NEGATIVE fixtures (scratch only).
Each fixture = input data-folder bytes (generated by master cff3f88 on a TEMP folder, then mutated), the fake exchange's
state, the legacy behaviour OBSERVED by repro_a..d (out_*.txt), and the REQUIRED NC-02 behaviour.
Output: fixtures/<ID>/input/*, fixtures/<ID>/fixture.json, fixtures/MANIFEST.json (sha256 per fixture contract)."""
import hashlib, json, os, shutil
import common as C

TS, E = C.setup()
OUT = os.path.join(C.HERE, 'fixtures')
SAFETY = ('state.json', 'state.json.bak', 'settings.json', 'settings.json.bak', 'install.json', 'install.json.bak')

# direction items (Codex #13 / PR #34 REC-01)
D1, D2, D3, D4 = ('D1 future schema: abort, state+backup byte-identical', 'D2 current damage: fail closed, keep evidence',
                  'D3 never an empty managed account', 'D4 explicit exchange/state reconciliation before management resumes')

# common NC-02 requirements (referenced by id in each fixture)
R = {
    'R-ABORT-RO': 'start-up aborts before ANY write to the store: every input file byte-identical after the attempt '
                  '(sha256 equal), no rename, no .bak rotation, no settings write; the refusal is reported out-of-band '
                  '(process exit code + boot incident log outside the store)',
    'R-NO-MANAGE': 'no AccountContext is created for the account: no order, cancel, stop repair, reconcile booking or '
                   'journal write is issued; protective orders already on the exchange are left untouched',
    'R-EVIDENCE': 'the damaged bytes are preserved bit-for-bit (copy-then-mark, never move-then-rewrite) and linked from a '
                  'durable incident record that survives restarts',
    'R-DURABLE-FAIL': 'the failed-closed condition is itself durable: a restart (with or without intervening saves) returns '
                      'to the same blocked state until an explicit reconciliation record exists',
    'R-RECON-GATE': 'management (and every new-risk path, MANUAL included) stays blocked until a reconciliation record '
                    'binds state generation G to an exchange snapshot that matches it (positions, open orders, protective '
                    'orders) or the owner adopts/flattens each difference explicitly; resuming entries alone never clears it',
    'R-NO-EMPTY': 'an initialized account (marker or any store generation or evidence present) can never load as an empty '
                  'portfolio; an empty portfolio is only legal for a first run whose exchange snapshot is flat (no '
                  'positions, no open orders) or after an explicit owner adoption record',
    'R-BACKUP-CANDIDATE': 'an older generation (backup) is offered as a reconciliation CANDIDATE, never silently promoted to '
                          'managed state; it becomes managed only after R-RECON-GATE passes against the exchange',
    'R-FIRST-RUN-FLAT': 'first-run initialization requires a successful exchange snapshot; a non-flat account blocks '
                        'initialization until the owner adopts or closes each position/order explicitly',
    'R-GEN-MONOTONIC': 'every store write carries (generation, writer_build, format_version, min_reader_version); a reader '
                       'that sees a generation written by a newer build, or a lower generation than the highest it has '
                       'seen (rollback/stale copy), aborts read-only (R-ABORT-RO)',
    'R-SINGLE-SOURCE': 'the account marker, the store and its backups are one versioned unit: one invalid member blocks the '
                       'unit; a backup can never silently clear an owner-confirmation requirement',
}


def build():
    e, tmp, fake = C.build(TS, E)
    return tmp, fake


def ex_state(fake):
    return dict(positions=[dict(symbol=s, side=d, qty=q) for (s, d), q in sorted(fake.pos.items()) if q > 1e-12],
                protective_orders=[dict(tag=k, symbol=v[0], side=v[1], qty=v[2], stop=v[3]) for k, v in sorted(fake.stops.items())])


def stamp(name, v):
    return lambda t: C.rewrite(os.path.join(t, name), lambda d: d.update(schema_version=v))


def trunc(name):
    def f(t):
        p = os.path.join(t, name)
        with open(p, 'rb') as fh: raw = fh.read()
        with open(p, 'wb') as fh: fh.write(raw[:40])
    return f


def badlot(name):
    def m(d): d['lots'][next(iter(d['lots']))]['qty'] = 'abc'
    return lambda t: C.rewrite(os.path.join(t, name), m)


def rm(*names):
    def f(t):
        for n in names:
            if os.path.exists(os.path.join(t, n)): os.remove(os.path.join(t, n))
    return f


def seq(*fs):
    return lambda t: [f(t) for f in fs]


def wipe(t):
    for n in SAFETY: rm(n)(t)


def v0_settings_only(t):
    rm('state.json', 'state.json.bak', 'install.json', 'install.json.bak', 'settings.json.bak')(t)
    C.rewrite(os.path.join(t, 'settings.json'), lambda d: d.pop('schema_version', None))


GATE = ('legacy resume gate checks install_block only (app.py:1225, telegram_ctl.py:524); MANUAL entries bypass '
        'ENTRIES_PAUSED (engine.py:3415); untracked needs 2 reconcile passes (engine.py:3268)')

F = [
 ('NF-01', 'future state.json (v99), current .bak', 'N', stamp('state.json', 99), 'a1',
  'start-up continues; state.json MOVED to state.json.corrupt-* (engine.py:1276-1278 via _version engine.py:550 -> SchemaError), '
  'older .bak promoted to managed lots (engine.py:1283-1292); settings rewritten to persist the pause; after 2 normal saves '
  'state.json.bak is overwritten (engine.py:483-487)', [D1, D4], ['R-ABORT-RO', 'R-NO-MANAGE', 'R-GEN-MONOTONIC']),
 ('NF-02', 'future state.json AND .bak (v2) - Codex reproduction', 'N', seq(stamp('state.json', 2), stamp('state.json.bak', 2)), 'a2',
  'both moved aside (engine.py:1278, 1294), failed_closed with ZERO lots while the exchange holds BTCUSDT LONG 1.0 + stop; '
  'untracked only after pass 2; owner resume allowed; a new ETHUSDT entry was SENT. ' + GATE, [D1, D3, D4],
  ['R-ABORT-RO', 'R-NO-MANAGE', 'R-NO-EMPTY']),
 ('NF-03', 'future settings.json (v2), current .bak', 'N', stamp('settings.json', 2), 'a3',
  'settings.json moved aside and rewritten from the older .bak (Engine.load_settings engine.py:1411 -> _load_safe); .bak rotated '
  'on the 2nd save', [D1], ['R-ABORT-RO', 'R-GEN-MONOTONIC']),
 ('NF-04', 'future settings.json AND .bak (v2)', 'N', seq(stamp('settings.json', 2), stamp('settings.json.bak', 2)), 'a4',
  'both moved aside; GLOBAL_DEFAULTS (40-coin universe, default sleeves) loaded and written to settings.json + .bak',
  [D1], ['R-ABORT-RO']),
 ('NF-05', 'future install.json (v2), current install.json.bak', 'N', stamp('install.json', 2), 'a5,a8',
  'install.json moved aside, account confirmation required (engine.py:1137-1144); on the NEXT restart install.json is silently '
  'restored from install.json.bak (engine.py:1126-1131) and the confirmation requirement disappears',
  [D1, D4], ['R-ABORT-RO', 'R-SINGLE-SOURCE']),
 ('NF-06', 'current state.json, future state.json.bak (v99)', 'N', stamp('state.json.bak', 99), 'a6',
  'no incident, entries open; the future .bak is overwritten by the first normal save (save_json engine.py:483-487)',
  [D1], ['R-ABORT-RO', 'R-GEN-MONOTONIC']),
 ('NF-07', 'failed-closed state is not durable (NF-02 inputs, then one save + restart)', 'N',
  seq(stamp('state.json', 2), stamp('state.json.bak', 2)), 'a7,b3',
  'after one cycle the empty state is saved as a valid v1 state.json; the next restart reports integrity={} and loads an '
  'empty managed account; only the persisted ENTRIES_PAUSED flag remains (owner-clearable)', [D2, D3, D4],
  ['R-DURABLE-FAIL', 'R-NO-EMPTY', 'R-RECON-GATE']),
 ('NF-08', 'truncated state.json (invalid JSON), good .bak', 'N', trunc('state.json'), 'b1',
  'evidence kept as .corrupt-*; older .bak promoted to managed lots with restored_from_bak; resume allowed, a new entry was SENT '
  'without any reconciliation record. ' + GATE, [D4], ['R-EVIDENCE', 'R-BACKUP-CANDIDATE', 'R-RECON-GATE']),
 ('NF-09', 'schema-invalid lot in state.json (qty="abc"), good .bak', 'N', badlot('state.json'), 'b2',
  'as NF-08 (SchemaError handled like damage, engine.py:1262-1263)', [D4], ['R-EVIDENCE', 'R-BACKUP-CANDIDATE', 'R-RECON-GATE']),
 ('NF-10', 'schema-invalid lot in state.json AND .bak', 'N', seq(badlot('state.json'), badlot('state.json.bak')), 'b3',
  'both moved aside; ZERO lots while the exchange holds BTCUSDT LONG 1.0; resume allowed; new entry SENT; after save+restart '
  'integrity={}', [D2, D3, D4], ['R-EVIDENCE', 'R-NO-EMPTY', 'R-DURABLE-FAIL', 'R-RECON-GATE']),
 ('NF-11', 'truncated state.json, .bak valid but OLDER and empty (saved before the trade)', 'N',
  seq(trunc('state.json'), lambda t: C.rewrite(os.path.join(t, 'state.json.bak'), lambda d: d.update(lots={}))), 'b4',
  'status restored_from_backup with ZERO lots; exchange position untracked after pass 2; resume allowed; new entry SENT',
  [D3, D4], ['R-BACKUP-CANDIDATE', 'R-NO-EMPTY', 'R-RECON-GATE']),
 ('NF-12', 'settings.json AND .bak truncated', 'N', seq(trunc('settings.json'), trunc('settings.json.bak')), 'b6',
  'evidence kept; defaults loaded and written over both paths', [D2], ['R-EVIDENCE', 'R-RECON-GATE']),
 ('NF-13', 'state.json persistently unreadable (OSError) at start-up', 'N', None, 'b7',
  'file left untouched and save-held (engine.py:1264-1270) - GOOD; but ZERO lots in memory, position untracked after pass 2, '
  'and resume is still allowed', [D3, D4], ['R-NO-MANAGE', 'R-DURABLE-FAIL', 'R-RECON-GATE']),
 ('NF-14', 'state.json + .bak deleted, install.json kept', 'N', rm('state.json', 'state.json.bak'), 'c1',
  'failed_closed ("missing on an already initialized installation", engine.py:1255-1257); ZERO lots; resume allowed; '
  'new entry SENT', [D3, D4], ['R-NO-EMPTY', 'R-DURABLE-FAIL', 'R-RECON-GATE']),
 ('NF-15', 'state + install marker deleted, versioned settings kept (POSITIVE control)', 'N',
  rm('state.json', 'state.json.bak', 'install.json', 'install.json.bak'), 'c2',
  'install_block set via _versioned_data (engine.py:1155-1170): resume and manual entries refused - correct; still zero lots '
  'in memory', [D3], ['R-NO-EMPTY', 'R-RECON-GATE']),
 ('NF-16', 'empty data folder (reinstall / moved LOCALAPPDATA), exchange NOT flat', 'N', wipe, 'c3',
  'treated as a first run: install.json written and bound to the account, entries OPEN, exchange position merely untracked; '
  'new entry SENT', [D3, D4], ['R-FIRST-RUN-FLAT']),
 ('NF-17', 'only an unversioned (v0) settings.json left, exchange NOT flat', 'N', v0_settings_only, 'c4',
  'legacy-install path: marker written, empty state, entries OPEN; new entry SENT', [D3, D4], ['R-FIRST-RUN-FLAT', 'R-NO-EMPTY']),
 ('NF-18', 'NEW (cff3f88) files read by OLD build (b8c11c8) - installer rollback across AUD-05', 'N-1', None, 'd1,d3',
  'OLD ignores schema_version/install.json/.bak, manages the lots and rewrites state.json (keeps the v1 label, .bak left stale); '
  'NEW later reads it back with no sign an older writer ran', [D4], ['R-GEN-MONOTONIC']),
 ('NF-19', 'NEW+1 (v2) files read by OLD build', 'N-1', seq(stamp('state.json', 2), stamp('state.json.bak', 2), stamp('settings.json', 2)), 'd4',
  'OLD loads v2 as if current, trades on it and writes state.json still labelled v2 with OLD semantics (version laundering)',
  [D1], ['R-GEN-MONOTONIC', 'R-ABORT-RO']),
 ('NF-20', 'damaged current state read by OLD build', 'N-1', trunc('state.json'), 'd6',
  'OLD silently starts EMPTY, entries OPEN, and OVERWRITES the damaged state.json (evidence destroyed)', [D2, D3],
  ['R-EVIDENCE', 'R-NO-EMPTY']),
 ('NF-21', 'OLD (unversioned, no marker) files read by NEW (POSITIVE control)', 'N', None, 'd2',
  'v0 -> v1 migration in place; legacy state owning lots -> install_mismatch, entries paused until THIS_ACCOUNT', [],
  ['R-GEN-MONOTONIC', 'R-RECON-GATE']),
]


def contract_sha(fx):
    c = {k: fx[k] for k in ('id', 'reader_build', 'input_files', 'exchange', 'nc02_required')}
    return hashlib.sha256(json.dumps(c, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


if os.path.exists(OUT): shutil.rmtree(OUT)
os.makedirs(OUT)
manifest = {}
for fid, title, reader, mutate, repro, observed, violates, req in F:
    tmp, fake = build()
    if mutate: mutate(tmp)
    d = os.path.join(OUT, fid); os.makedirs(os.path.join(d, 'input'))
    files = {}
    for n in SAFETY:
        p = os.path.join(tmp, n)
        if os.path.exists(p):
            shutil.copyfile(p, os.path.join(d, 'input', n))
            with open(p, 'rb') as fh: files[n] = hashlib.sha256(fh.read()).hexdigest()
    extra = {}
    if fid == 'NF-13': extra['inject'] = 'state.json read raises PermissionError(13) on every attempt'
    if fid == 'NF-18': extra['note'] = 'inputs are untouched NEW output; reader is the pre-AUD-05 build'
    if fid == 'NF-21': extra['note'] = 'input must be regenerated by b8c11c8 (rollback_worker.py old_src init); the files here are NEW-format placeholders'
    if fid == 'NF-07': extra['steps'] = ['start', 'one state save', 'restart']
    fx = dict(id=fid, title=title, reader_build=reader, source_repro=repro, input_files=files, exchange=ex_state(fake),
              legacy_observed=dict(build='cff3f88' if reader == 'N' else 'b8c11c8', behaviour=observed),
              violates=violates, nc02_required={r: R[r] for r in req}, **extra)
    fx['contract_sha'] = contract_sha(fx)
    with open(os.path.join(d, 'fixture.json'), 'w') as fh: json.dump(fx, fh, indent=2)
    manifest[fid] = fx['contract_sha']
with open(os.path.join(OUT, 'MANIFEST.json'), 'w') as fh:
    json.dump(dict(schema='nc02-negative-fixtures/0-draft', generated_from='master cff3f88 (scratch, TEMP data dirs)',
                   requirements=R, fixtures=manifest), fh, indent=2)
print(f'{len(manifest)} fixtures written to {OUT}')
E.close_fill_writers(2.0)
